apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: app-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-java
  template:
    metadata:
      labels:
        app: app-java
    spec:
      containers:
        - name: app-java
          image: educavalieri/java-application-build
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-java
spec:
  selector:
    app: app-java
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer