name: java-application
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkou project
        uses: actions/checkout@v4
      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: | 
            educavalieri/java-application-build:${{github.run_number}}
            educavalieri/java-application-build:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Checkou project
        uses: actions/checkout@v4
      - name: k8s set context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
      - name: Deploy to k8s
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            deployment.yaml
          images: educavalieri/java-application-build:${{github.run_number}}

        
        
